apiVersion: apps/v1
kind: Deployment
metadata:
  name: venue-service
  namespace: cricheroes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: venue-service
  template:
    metadata:
      labels:
        app: venue-service
    spec:
      containers:
      - name: venue-service
        image: cricheroes/venue-service:latest
        ports:
        - containerPort: 3017
        envFrom:
        - configMapRef:
            name: venue-service-config
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: venue-service
  namespace: cricheroes
spec:
  selector:
    app: venue-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3017
  type: ClusterIP
