export enum UserRole {
  PLAYER = 'PLAYER',
  SCORER = 'SCORER',
  UMPIRE = 'UMPIRE',
  COMMENTATOR = 'COMMENTATOR',
  ORGANIZER = 'ORGANIZER',
  ADMIN = 'ADMIN',
}

export enum OTPType {
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  VERIFY_PHONE = 'VERIFY_PHONE',
}

export enum DeviceType {
  ANDROID = 'ANDROID',
  IOS = 'IOS',
  WEB = 'WEB',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum BattingStyle {
  RIGHT_HAND = 'RIGHT_HAND',
  LEFT_HAND = 'LEFT_HAND',
}

export enum BowlingStyle {
  RIGHT_ARM_FAST = 'RIGHT_ARM_FAST',
  RIGHT_ARM_MEDIUM = 'RIGHT_ARM_MEDIUM',
  LEFT_ARM_FAST = 'LEFT_ARM_FAST',
  LEFT_ARM_MEDIUM = 'LEFT_ARM_MEDIUM',
  RIGHT_ARM_OFF_SPIN = 'RIGHT_ARM_OFF_SPIN',
  RIGHT_ARM_LEG_SPIN = 'RIGHT_ARM_LEG_SPIN',
  LEFT_ARM_ORTHODOX = 'LEFT_ARM_ORTHODOX',
  LEFT_ARM_CHINAMAN = 'LEFT_ARM_CHINAMAN',
  NONE = 'NONE',
}

export enum PlayerType {
  BATSMAN = 'BATSMAN',
  BOWLER = 'BOWLER',
  ALL_ROUNDER = 'ALL_ROUNDER',
  WICKET_KEEPER = 'WICKET_KEEPER',
}

export enum TeamMemberRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  PLAYER = 'PLAYER',
}

export enum InviteStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum MatchType {
  LIMITED_OVERS = 'LIMITED_OVERS',
  TEST = 'TEST',
  T20 = 'T20',
  ODI = 'ODI',
  T10 = 'T10',
  CUSTOM = 'CUSTOM',
  THE_HUNDRED = 'THE_HUNDRED',
  PAIR_CRICKET = 'PAIR_CRICKET',
}

export enum BallType {
  LEATHER = 'LEATHER',
  TENNIS = 'TENNIS',
  OTHER = 'OTHER',
}

export enum PitchType {
  TURF = 'TURF',
  CEMENT = 'CEMENT',
  MATTING = 'MATTING',
  ARTIFICIAL = 'ARTIFICIAL',
  OTHER = 'OTHER',
}

export enum MatchStatus {
  UPCOMING = 'UPCOMING',
  LIVE = 'LIVE',
  INNINGS_BREAK = 'INNINGS_BREAK',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
  CANCELLED = 'CANCELLED',
  NO_RESULT = 'NO_RESULT',
}

export enum TossDecision {
  BAT = 'BAT',
  BOWL = 'BOWL',
}

export enum WinType {
  RUNS = 'RUNS',
  WICKETS = 'WICKETS',
  TIE = 'TIE',
  DRAW = 'DRAW',
  SUPER_OVER = 'SUPER_OVER',
  DLS = 'DLS',
  NO_RESULT = 'NO_RESULT',
}

export enum DismissalType {
  BOWLED = 'BOWLED',
  CAUGHT = 'CAUGHT',
  LBW = 'LBW',
  RUN_OUT = 'RUN_OUT',
  STUMPED = 'STUMPED',
  HIT_WICKET = 'HIT_WICKET',
  CAUGHT_AND_BOWLED = 'CAUGHT_AND_BOWLED',
  RETIRED_HURT = 'RETIRED_HURT',
  RETIRED_OUT = 'RETIRED_OUT',
  TIMED_OUT = 'TIMED_OUT',
  OBSTRUCTING = 'OBSTRUCTING',
  HANDLED_BALL = 'HANDLED_BALL',
  HIT_BALL_TWICE = 'HIT_BALL_TWICE',
}

export enum InningsStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DECLARED = 'DECLARED',
}

export enum ExtraType {
  NONE = 'NONE',
  WIDE = 'WIDE',
  NO_BALL = 'NO_BALL',
  BYE = 'BYE',
  LEG_BYE = 'LEG_BYE',
  PENALTY = 'PENALTY',
}

export enum ShotType {
  STRAIGHT = 'STRAIGHT',
  COVER = 'COVER',
  MID_WICKET = 'MID_WICKET',
  SQUARE_LEG = 'SQUARE_LEG',
  POINT = 'POINT',
  FINE_LEG = 'FINE_LEG',
  THIRD_MAN = 'THIRD_MAN',
  LONG_ON = 'LONG_ON',
  LONG_OFF = 'LONG_OFF',
  MID_ON = 'MID_ON',
  MID_OFF = 'MID_OFF',
  OTHER = 'OTHER',
}

export enum PitchLength {
  SHORT = 'SHORT',
  GOOD_LENGTH = 'GOOD_LENGTH',
  FULL = 'FULL',
  YORKER = 'YORKER',
  FULL_TOSS = 'FULL_TOSS',
}

export enum TournamentFormat {
  LEAGUE = 'LEAGUE',
  KNOCKOUT = 'KNOCKOUT',
  LEAGUE_CUM_KNOCKOUT = 'LEAGUE_CUM_KNOCKOUT',
  SUPER_OVER = 'SUPER_OVER',
  BOX_CRICKET = 'BOX_CRICKET',
  CUSTOM = 'CUSTOM',
}

export enum TournamentTeamStatus {
  REGISTERED = 'REGISTERED',
  CONFIRMED = 'CONFIRMED',
  ELIMINATED = 'ELIMINATED',
  WINNER = 'WINNER',
  RUNNER_UP = 'RUNNER_UP',
}

export enum RoundType {
  GROUP_STAGE = 'GROUP_STAGE',
  QUARTER_FINAL = 'QUARTER_FINAL',
  SEMI_FINAL = 'SEMI_FINAL',
  FINAL = 'FINAL',
  THIRD_PLACE = 'THIRD_PLACE',
  ELIMINATOR = 'ELIMINATOR',
  QUALIFIER = 'QUALIFIER',
}

export enum TournamentStatus {
  DRAFT = 'DRAFT',
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  UPCOMING = 'UPCOMING',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum PostType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  POLL = 'POLL',
  MATCH_HIGHLIGHT = 'MATCH_HIGHLIGHT',
  ACHIEVEMENT = 'ACHIEVEMENT',
  MILESTONE = 'MILESTONE',
}

export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
}

export enum Visibility {
  PUBLIC = 'PUBLIC',
  FOLLOWERS = 'FOLLOWERS',
  PRIVATE = 'PRIVATE',
}

export enum NotificationType {
  MATCH_STARTED = 'MATCH_STARTED',
  MATCH_COMPLETED = 'MATCH_COMPLETED',
  MATCH_INVITE = 'MATCH_INVITE',
  TEAM_INVITE = 'TEAM_INVITE',
  TEAM_JOINED = 'TEAM_JOINED',
  TOURNAMENT_STARTED = 'TOURNAMENT_STARTED',
  TOURNAMENT_UPDATE = 'TOURNAMENT_UPDATE',
  WICKET_FALLEN = 'WICKET_FALLEN',
  MILESTONE_REACHED = 'MILESTONE_REACHED',
  FOLLOW = 'FOLLOW',
  LIKE = 'LIKE',
  COMMENT = 'COMMENT',
  MENTION = 'MENTION',
  SCORE_UPDATE = 'SCORE_UPDATE',
  ACHIEVEMENT = 'ACHIEVEMENT',
  SYSTEM = 'SYSTEM',
}

export enum LeaderboardType {
  GLOBAL = 'GLOBAL',
  TOURNAMENT = 'TOURNAMENT',
  LOCAL = 'LOCAL',
  MONTHLY = 'MONTHLY',
  WEEKLY = 'WEEKLY',
}

export enum LeaderboardCategory {
  MOST_RUNS = 'MOST_RUNS',
  HIGHEST_AVERAGE = 'HIGHEST_AVERAGE',
  HIGHEST_STRIKE_RATE = 'HIGHEST_STRIKE_RATE',
  MOST_FIFTIES = 'MOST_FIFTIES',
  MOST_HUNDREDS = 'MOST_HUNDREDS',
  MOST_SIXES = 'MOST_SIXES',
  MOST_FOURS = 'MOST_FOURS',
  MOST_WICKETS = 'MOST_WICKETS',
  BEST_BOWLING_AVERAGE = 'BEST_BOWLING_AVERAGE',
  BEST_ECONOMY = 'BEST_ECONOMY',
  MOST_CATCHES = 'MOST_CATCHES',
  MOST_STUMPINGS = 'MOST_STUMPINGS',
  MVP = 'MVP',
  MOST_MATCHES = 'MOST_MATCHES',
  MOST_MOM_AWARDS = 'MOST_MOM_AWARDS',
}
