apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  namespace: cricheroes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
      - name: subscription-service
        image: cricheroes/subscription-service:latest
        ports:
        - containerPort: 3016
        envFrom:
        - configMapRef:
            name: subscription-service-config
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  namespace: cricheroes
spec:
  selector:
    app: subscription-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3016
  type: ClusterIP
